# SPDX-FileCopyrightText: 2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
#
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
