version = 1
SPDX-PackageName = "swagger-ui-plugin-diff-highlight"
SPDX-PackageSupplier = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/swagger-ui-plugin-diff-highlight"

[[annotations]]
path = [
    "repolinter.json",
    "NOTICE",
    ".gitignore",
    ".prettierignore",
    ".npmrc",
    ".prettierrc",
    ".tool-versions",
    ".github/CODEOWNERS",
    "package.json",
    "package-lock.json",
    "example/.npmrc",
    "example/package.json",
    "example/package-lock.json",
    "example/src/specs/diffSpec.json",
    "example/src/specs/latestSpec.json",
]

SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "THIRD-PARTY-LICENSES/**"
precedence = "override"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "Apache-2.0"
